# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_ieee754_exp <- function(x) {
    .Call(`_expTest_rcpp_ieee754_exp`, x)
}

rcpp_ieee754_log <- function(x) {
    .Call(`_expTest_rcpp_ieee754_log`, x)
}

